services:
  # The Backend API Service
  - type: web
    name: task-api-backend
    env: docker
    image:
      url: satyamamrutkar/task-tracker-backend:latest
    # FIX: 'healthCheck' block is replaced with the correct 'healthCheckPath' key.
    healthCheckPath: /api/tasks
    # FIX: The 'ports' block is removed. Render automatically uses the port
    # exposed in your Dockerfile (EXPOSE 3000).
    autoDeploy: false

  # The Frontend Service
  - type: web
    name: task-app-frontend
    env: docker
    image:
      url: satyamamrutkar/task-tracker-frontend:latest
    # FIX: The 'ports' block is removed. Render automatically uses the port
    # exposed by the Nginx image in your Dockerfile (port 80).
    autoDeploy: false
    envVars:
      - key: DOCKER_CMD
        value: |
          echo "window.config = { API_URL: '${task-api-backend.RENDER_EXTERNAL_URL}' }" > /usr/share/nginx/html/config.js && nginx -g 'daemon off;'