services:
  # Backend API (Node.js)
  - type: web
    name: task-api-backend
    env: docker
    dockerfilePath: ./task-api/Dockerfile
    buildContext: ./task-api
    envVars:
      - key: PORT
        value: 3000
    plan: free
    autoDeploy: false

  # Frontend (Nginx serving static files)
  - type: web
    name: task-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    buildContext: .
    envVars:
      - key: PORT
        value: 80
    plan: free
    autoDeploy: false
