services:
  # The Backend API Service
  - type: web
    name: task-api-backend
    runtime: image # FIX: Changed 'env: docker' to 'runtime: image'
    image:
      url: satyamamrutkar/task-full-backend:latest
    healthCheckPath: /api/tasks
    autoDeploy: false

  # The Frontend Service
  - type: web
    name: task-app-frontend
    runtime: image # FIX: Changed 'env: docker' to 'runtime: image'
    image:
      url: satyamamrutkar/task-full-frontend:latest
    autoDeploy: false
    envVars:
      - key: DOCKER_CMD
        value: |
          echo "window.config = { API_URL: '${task-api-backend.RENDER_EXTERNAL_URL}' }" > /usr/share/nginx/html/config.js && nginx -g 'daemon off;'